{
 "title": "ArgoCD Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "General Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Info Logs",
     "type": "logs",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{ kubernetes_namespace_name=\"openshift-gitops\"} |= \"level=info\" |json"
      }
     ]
    },
    {
     "title": "Logs with Errors",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "{ kubernetes_namespace_name=\"openshift-gitops\"} |= \"error\" |json"
      }
     ]
    },
    {
     "title": "ArgoCD Logs Count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "sum(count_over_time({ kubernetes_namespace_name=\"openshift-gitops\"}[5m]))"
      }
     ]
    },
    {
     "title": "ArgoCD Error Logs Count",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "sum(count_over_time(({kubernetes_namespace_name=\"openshift-gitops\"} |= \"error\")[1m])) or vector(0)",
       "legendFormat": "Error Logs"
      }
     ]
    }
   ]
  },
  {
   "title": "Sync Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Logs",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{ kubernetes_namespace_name=\"openshift-gitops\"} |= \"initiated sync\" | regexp \"(?P<user>[^\\\"]+) initiated sync\" | label_format user=\"{{ .user }}\""
      }
     ]
    },
    {
     "title": "Sync operations by user (over 15 minutes)",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(count_over_time({ kubernetes_namespace_name=\"openshift-gitops\"} |= \"initiated sync\" | regexp \"(?P<user>[^\\\"]+) initiated sync\" | label_format user=\"{{ .user }}\"[15m])) by (user)",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "Sync operations by user (over 15 minutes)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(count_over_time({ kubernetes_namespace_name=\"openshift-gitops\"} |= \"initiated sync\" | regexp \"(?P<user>[^\\\"]+) initiated sync\" | label_format user=\"{{ .user }}\"[15m])) by (user)",
       "legendFormat": "{{user}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"openshift-gitops\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"openshift-gitops\", container!=\"\", container!=\"POD\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Overview",
     "type": "table",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_resource_request{namespace=\"openshift-gitops\", container!=\"\", container!=\"POD\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"openshift-gitops\", container!=\"\", container!=\"POD\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"openshift-gitops\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Sync Operations by Application",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(argocd_app_sync_total) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Git Latency (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(argocd_git_request_duration_seconds_count[5m])) by (request_type)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Reconciliation Performance (seconds)",
     "type": "heatmap",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(argocd_app_reconcile_bucket{namespace=\"openshift-gitops\"}[1m])) by (le)"
      }
     ]
    },
    {
     "title": "Out Of Sync Applications",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{health_status=\"Healthy\",sync_status=\"OutOfSync\",namespace=\"openshift-gitops\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "ArgoCD Events by Resource",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(rate(argocd_cluster_events_total[1m])) by (kind)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}