apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: openshift-logging
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
