kind: Secret
apiVersion: v1
metadata:
  name: minio-s3
  namespace: openshift-logging
data:
  access_key_id: bWluaW8=
  access_key_secret: bWluaW8xMjM=
  bucketnames: bG9raQ==
  endpoint: aHR0cHM6Ly9taW5pby1taW5pby5hcHBzLnR6NWd3LmR5bmFtaWMucmVkaGF0d29ya3Nob3BzLmlv
type: Opaque

