apiVersion: v1
stringData:
  loki.yaml: |
    type: s3
    config:
      bucket: "loki"
      endpoint: "minio:9000"
      insecure: true
      access_key: "minio"
      secret_key: "minio123"
kind: Secret
metadata:
  name: loki-object-storage
type: Opaque
